# Generated by Django 5.0.4 on 2024-05-06 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commented_at',
            field=models.DateField(default=datetime.datetime(2024, 5, 6, 0, 19, 37, 741302), verbose_name='Comment created at'),
        ),
    ]
