# Generated by Django 5.0.4 on 2024-05-04 02:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='offered_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Offer created at'),
        ),
    ]
