# Generated by Django 5.0.4 on 2024-05-04 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commented_at',
            field=models.DateField(default=datetime.datetime(2024, 5, 4, 2, 49, 4, 106816), verbose_name='Comment created at'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='offered_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Offer created at'),
        ),
        migrations.AlterField(
            model_name='winners',
            name='timestamp',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Product winned at'),
        ),
    ]
